apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recommendations-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendations
    spec:
      containers:
      - image: urosbajc/recommendations:0.2
        name: messaging
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://recommendations:8087
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8087
          name: server
          protocol: TCP
        resources:
          requests:
            cpu: 200m
